repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the ref you want to point at
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: .*\.js\.snap$
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic", "types-setuptools"]
